# Generated by Django 6.0.5 on 2026-05-12 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('national_id', models.CharField(blank=True, max_length=30, null=True)),
                ('move_in_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
            ],
        ),
    ]
